esphome:
  name: chambre1                      #ADAPT TO YOUR NAME ROOM 
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "xxxxxxxxxxxxx"               #ADAPT TO YOUR WIFI SSID 
  password: "xxxxxxxxxxxxxxxxxxxx"    #ADAPT TO YOUR WIFI PWD

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxxxxxx"                 #ADAPT YOUR PERSONNAL PWD FOR LINK IN HA  

ota:
  password: "xxxxxxxx"                #ADAPT YOUR PERSONNAL PWD FOR LINK IN EspHome 

binary_sensor:
  - platform: gpio
    pin: GPIO13
    name: "Garage PIR Sensor"
    device_class: motion
  
# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  vertical_flip: false
  horizontal_mirror: false
  resolution: 640x480 

  name: chambre1                   #ADAPT TO YOUR NAME ROOM
  # ... Frame Settings

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: $hostname lightc1